# Techno-economic data for RO system chemicals
# These supplement WaterTAP's existing chemical_addition.yaml
# All costs in USD_2018 per kg
# Capital parameters follow WaterTAP's power law: Cost = A * Flow^B

hydrochloric_acid:
  chemical_dosage:
    value: 10  # Default dosage (will be overridden by pH optimizer)
    units: mg/L
  solution_density:
    value: 1190  # For 37% HCl solution
    units: kg/m^3
  ratio_in_solution:
    value: 0.37  # 37% HCl
    units: dimensionless
  capital_cost:
    basis: chemical_flow_mass
    cost_factor: TPEC
    capital_a_parameter:
      value: 1800  # Dosing system capital cost
      units: USD_2018
    capital_b_parameter:
      value: 0.65  # Scaling exponent
      units: dimensionless
  chemical_cost:
    value: 0.17  # $/kg for 37% HCl
    units: USD_2018/kg

sulfuric_acid:
  chemical_dosage:
    value: 10  # Default dosage (will be overridden by pH optimizer)
    units: mg/L
  solution_density:
    value: 1840  # For 98% H2SO4
    units: kg/m^3
  ratio_in_solution:
    value: 0.98  # 98% H2SO4
    units: dimensionless
  capital_cost:
    basis: chemical_flow_mass
    cost_factor: TPEC
    capital_a_parameter:
      value: 1800  # Dosing system capital cost
      units: USD_2018
    capital_b_parameter:
      value: 0.65  # Scaling exponent
      units: dimensionless
  chemical_cost:
    value: 0.10  # $/kg for 98% H2SO4
    units: USD_2018/kg

# Caustic soda is already in WaterTAP's database, but we override the cost
caustic_soda_override:
  chemical_cost:
    value: 0.35  # $/kg for 50% NaOH solution
    units: USD_2018/kg

# Antiscalant - already defined as "anti-scalant" in WaterTAP
# But add specific product costs for RO systems
antiscalant_suez:
  chemical_cost:
    value: 2.50  # $/kg for SUEZ products
    units: USD_2018/kg
  recommended_dose:
    value: 3.0  # mg/L typical
    units: mg/L

antiscalant_nalco:
  chemical_cost:
    value: 2.75  # $/kg for Nalco products
    units: USD_2018/kg
  recommended_dose:
    value: 4.0  # mg/L typical
    units: mg/L

antiscalant_avista:
  chemical_cost:
    value: 2.25  # $/kg for Avista products
    units: USD_2018/kg
  recommended_dose:
    value: 3.5  # mg/L typical
    units: mg/L

# CIP chemicals
cip_acid:
  # Typically citric acid or sulfuric acid
  chemical_cost:
    value: 0.50  # $/kg for citric acid
    units: USD_2018/kg
  concentration:
    value: 0.02  # 2% solution typical
    units: dimensionless

cip_base:
  # Typically sodium hydroxide
  chemical_cost:
    value: 0.35  # $/kg for NaOH
    units: USD_2018/kg
  concentration:
    value: 0.02  # 2% solution typical
    units: dimensionless

cip_surfactant:
  # Detergent/surfactant for membrane cleaning
  chemical_cost:
    value: 3.00  # $/kg for membrane cleaner
    units: USD_2018/kg
  concentration:
    value: 0.01  # 1% solution typical
    units: dimensionless

# Operating parameters
chemical_parameters:
  cip_frequency_per_year:
    value: 4  # Quarterly CIP typical
    units: 1/year
  cip_duration_hours:
    value: 4  # 4-hour CIP cycle typical
    units: hours
  antiscalant_efficiency:
    value: 0.95  # 95% dosing efficiency
    units: dimensionless