# RO Design MCP Server - System Default Configuration
# This file contains all default parameters used by the optimization algorithms

# Element and vessel specifications
element:
  standard_area_m2: 37.16  # 400 ft² standard element
  elements_per_vessel: 7

# Membrane dimensions for spiral wound modules
membrane_dimensions:
  8040:  # 8" diameter x 40" length standard element
    diameter_m: 0.2032  # 8 inches
    length_m: 1.016     # 40 inches
    active_area_m2: 37.16  # 400 ft² per element
    elements_per_vessel: 7

# Stage-specific design parameters
stage_defaults:
  flux_targets_lmh: [18, 15, 12]  # LMH for stages 1, 2, 3+
  min_concentrate_flow_m3h: [3.5, 3.8, 4.0]  # m³/h per vessel
  
# Flux and recovery tolerances
tolerances:
  flux_tolerance: 0.1  # ±10% of target
  recovery_tolerance: 0.02  # 2% tolerance
  convergence_tolerance: 0.01  # m³/h for recycle optimization

# Optimization parameters
optimization:
  max_stages: 3  # Industry standard maximum
  max_recycle_ratio: 0.9  # Maximum allowed recycle ratio
  min_vessels_per_stage: 1
  max_vessels_per_stage: 100

# Membrane properties by type
# Note: These are Solution-Diffusion (SD) model parameters only
# Literature-based values from peer-reviewed sources
membrane_properties:
  # Dow FilmTec BW30-400 - Standard brackish water membrane
  bw30_400:
    A_w: 9.63e-12   # m/s/Pa - Water permeability (MDPI Water 2019, 11(1), 152)
    B_s: 5.58e-8    # m/s - Salt permeability (MDPI Water 2019, 11(1), 152)
    pressure_drop:
      stage1: 2.0e5  # Pa (2 bar)
      stage2: 1.5e5  # Pa (1.5 bar)
      stage3: 1.0e5  # Pa (1 bar)
    max_pressure: 4137000  # Pa (41.37 bar / 600 psi)
    
  # Dow FilmTec ECO PRO-400 - High permeability brackish water
  eco_pro_400:
    A_w: 1.60e-11   # m/s/Pa - Water permeability (MDPI Water 2019, 11(1), 152)
    B_s: 4.24e-8    # m/s - Salt permeability (MDPI Water 2019, 11(1), 152)
    pressure_drop:
      stage1: 2.0e5  # Pa (2 bar)
      stage2: 1.5e5  # Pa (1.5 bar)
      stage3: 1.0e5  # Pa (1 bar)
    max_pressure: 4137000  # Pa (41.37 bar / 600 psi)
    
  # Dow FilmTec FORTILIFE CR100 PRO-400 - Chemical resistant brackish
  cr100_pro_400:
    A_w: 1.06e-11   # m/s/Pa - Water permeability (MDPI Water 2019, 11(1), 152)
    B_s: 4.16e-8    # m/s - Salt permeability (MDPI Water 2019, 11(1), 152)
    pressure_drop:
      stage1: 2.0e5  # Pa (2 bar)
      stage2: 1.5e5  # Pa (1.5 bar)
      stage3: 1.0e5  # Pa (1 bar)
    max_pressure: 4137000  # Pa (41.37 bar / 600 psi)
    
  # Generic types for backward compatibility
  brackish:
    A_w: 9.63e-12   # m/s/Pa - Using BW30-400 as default
    B_s: 5.58e-8    # m/s - Using BW30-400 as default
    pressure_drop:
      stage1: 2.0e5  # Pa (2 bar)
      stage2: 1.5e5  # Pa (1.5 bar)
      stage3: 1.0e5  # Pa (1 bar)
    max_pressure: 4137000  # Pa (41.37 bar)
    
  seawater:
    A_w: 3.0e-12    # m/s/Pa - Typical for SW membranes
    B_s: 1.5e-8     # m/s - Typical for SW membranes
    pressure_drop:
      stage1: 3.0e5  # Pa (3 bar)
      stage2: 2.5e5  # Pa (2.5 bar)
      stage3: 2.0e5  # Pa (2 bar)
    max_pressure: 8270000  # Pa (82.7 bar)

# Economic parameters (for future use)
economics:
  electricity_cost_usd_kwh: 0.07
  membrane_cost_usd_m2: 30
  utilization_factor: 0.9
  pump_efficiency: 0.8

# Logging configuration
logging:
  level: INFO  # Options: DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"